In [1]:
import pandas as pd
import numpy as np
import math

# 删除某行某列——.drop(行名,axis=0,1)0是行，1是列

In [2]:
df=pd.read_csv('F:\\Data and code\\data\\FSDA\\phoneme.data')
df.index = df.iloc[:,0]
df = df.drop('row.names',1)
df

,x.1,x.2,x.3,x.4,x.5,x.6,x.7,x.8,x.9,x.10,...,x.249,x.250,x.251,x.252,x.253,x.254,x.255,x.256,g,speaker
row.names,,,,,,,,,,,,,,,,,,,,,
1,9.85770,9.20711,9.81689,9.01692,9.05675,8.92518,11.28308,11.52980,10.79713,9.04747,...,12.68076,11.20767,13.69394,13.72055,12.16628,12.92489,12.51195,9.75527,sh,train.dr1.mcpm0.sa1
2,13.23079,14.19189,15.34428,18.11737,19.53875,18.32726,17.34169,17.16861,19.63557,20.15212,...,8.45714,8.77266,9.59717,8.45336,7.57730,5.38504,9.43063,8.59328,iy,train.dr1.mcpm0.sa1
3,10.81889,9.07615,9.77940,12.20135,12.59005,10.53364,8.54693,9.46049,11.96755,12.05282,...,5.00824,5.51019,5.95725,7.04992,7.02469,6.58416,6.27058,3.85042,dcl,train.dr1.mcpm0.sa1
4,10.53679,9.12147,10.84621,13.92331,13.52476,10.27831,8.97459,11.57109,12.35839,10.47826,...,5.85688,5.40324,6.07126,5.30651,4.27412,3.63384,3.22823,4.63123,dcl,train.dr1.mcpm0.sa1
5,12.96705,13.69454,14.91182,18.22292,18.45390,17.25760,17.79614,17.76387,18.99632,17.40394,...,8.00151,7.58624,6.65202,7.69109,6.93683,7.03600,7.01278,8.52197,aa,train.dr1.mcpm0.sa1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4505,11.38394,10.21040,16.32658,18.30125,16.91804,10.90029,17.10393,19.37741,18.46994,14.12358,...,9.79996,7.85765,6.92906,8.89384,8.04072,6.99793,6.07412,7.32593,iy,test.dr8.mslb0.sa1
4506,12.01774,11.86761,16.34707,18.05214,15.97599,12.86022,16.83436,18.38985,15.90410,13.18483,...,8.20094,8.40645,7.49869,9.56486,10.86934,8.85308,9.88492,6.35767,aa,test.dr8.mslb0.sa1
4507,12.30174,12.40383,9.06497,12.43750,13.48388,13.52034,12.97796,11.58782,12.54174,14.09863,...,12.83836,10.62525,10.15274,9.59347,10.66338,9.88007,10.82203,12.00199,sh,test.dr8.mslb0.sa1
4508,8.39388,9.84770,16.24534,17.35311,14.80537,12.72429,17.01145,17.54733,14.35809,13.65718,...,4.57875,7.91262,8.08014,9.25111,9.56086,9.37979,6.83916,8.54817,ao,test.dr8.mslb0.sa1
4509,8.14032,9.93753,16.30187,17.31425,14.40116,13.52353,16.85938,17.14016,13.06426,15.32220,...,5.27574,6.95050,7.83462,7.96455,7.26886,7.08945,7.72929,6.42167,ao,test.dr8.mslb0.sa1

# 改行名列名——df.index\columns

* 行名一般是index，列名一般是columns
* 读取文件的时候直接搞名字是:

    header = None ；index_col = ?[第几列作为index名]
    
* 读取后对行列名进行命名是（这里是复制上去的形式）：

    df.columns = df.iloc[0,:];df.index = df.iloc[:,0]
    
* 删除某行某列：
    
    df.drop('行/列名'，0/1)

In [3]:
df=pd.read_csv('F:\\Data and code\\data\\FSDA\\phoneme.data')
df.index = df.iloc[:,0]
df = df.drop('row.names',1)

df == pd.read_csv('F:\\Data and code\\data\\FSDA\\phoneme.data',index_col = 0)

,x.1,x.2,x.3,x.4,x.5,x.6,x.7,x.8,x.9,x.10,...,x.249,x.250,x.251,x.252,x.253,x.254,x.255,x.256,g,speaker
row.names,,,,,,,,,,,,,,,,,,,,,
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
5,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4505,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4506,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4507,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4508,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4509,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [4]:
df

,x.1,x.2,x.3,x.4,x.5,x.6,x.7,x.8,x.9,x.10,...,x.249,x.250,x.251,x.252,x.253,x.254,x.255,x.256,g,speaker
row.names,,,,,,,,,,,,,,,,,,,,,
1,9.85770,9.20711,9.81689,9.01692,9.05675,8.92518,11.28308,11.52980,10.79713,9.04747,...,12.68076,11.20767,13.69394,13.72055,12.16628,12.92489,12.51195,9.75527,sh,train.dr1.mcpm0.sa1
2,13.23079,14.19189,15.34428,18.11737,19.53875,18.32726,17.34169,17.16861,19.63557,20.15212,...,8.45714,8.77266,9.59717,8.45336,7.57730,5.38504,9.43063,8.59328,iy,train.dr1.mcpm0.sa1
3,10.81889,9.07615,9.77940,12.20135,12.59005,10.53364,8.54693,9.46049,11.96755,12.05282,...,5.00824,5.51019,5.95725,7.04992,7.02469,6.58416,6.27058,3.85042,dcl,train.dr1.mcpm0.sa1
4,10.53679,9.12147,10.84621,13.92331,13.52476,10.27831,8.97459,11.57109,12.35839,10.47826,...,5.85688,5.40324,6.07126,5.30651,4.27412,3.63384,3.22823,4.63123,dcl,train.dr1.mcpm0.sa1
5,12.96705,13.69454,14.91182,18.22292,18.45390,17.25760,17.79614,17.76387,18.99632,17.40394,...,8.00151,7.58624,6.65202,7.69109,6.93683,7.03600,7.01278,8.52197,aa,train.dr1.mcpm0.sa1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4505,11.38394,10.21040,16.32658,18.30125,16.91804,10.90029,17.10393,19.37741,18.46994,14.12358,...,9.79996,7.85765,6.92906,8.89384,8.04072,6.99793,6.07412,7.32593,iy,test.dr8.mslb0.sa1
4506,12.01774,11.86761,16.34707,18.05214,15.97599,12.86022,16.83436,18.38985,15.90410,13.18483,...,8.20094,8.40645,7.49869,9.56486,10.86934,8.85308,9.88492,6.35767,aa,test.dr8.mslb0.sa1
4507,12.30174,12.40383,9.06497,12.43750,13.48388,13.52034,12.97796,11.58782,12.54174,14.09863,...,12.83836,10.62525,10.15274,9.59347,10.66338,9.88007,10.82203,12.00199,sh,test.dr8.mslb0.sa1
4508,8.39388,9.84770,16.24534,17.35311,14.80537,12.72429,17.01145,17.54733,14.35809,13.65718,...,4.57875,7.91262,8.08014,9.25111,9.56086,9.37979,6.83916,8.54817,ao,test.dr8.mslb0.sa1
4509,8.14032,9.93753,16.30187,17.31425,14.40116,13.52353,16.85938,17.14016,13.06426,15.32220,...,5.27574,6.95050,7.83462,7.96455,7.26886,7.08945,7.72929,6.42167,ao,test.dr8.mslb0.sa1

# 筛选指定列值行

1. 先iloc出列再loc出对应Ture的行
2. 直接用df.query()——把字符串形式的查询表达式传入 query 方法来查询数据

* qurey

In [5]:
df=pd.read_csv('F:\\Data and code\\data\\FSDA\\phoneme.data',index_col = 0)

In [6]:
df1 = df.query('((g == "sh")&((speaker == "train.dr1.mcpm0.sa1" )| (speaker == "train.dr5.mwac0.sa1")))')

In [7]:
df1 = df.query('((g == "sh")&'
               '((speaker == "train.dr1.mcpm0.sa1")|(speaker == "train.dr5.mwac0.sa1"))'
               ')')

In [8]:
df1 = df.query('((g == "sh")&'
               '((speaker in ["train.dr1.mcpm0.sa1","train.dr5.mwac0.sa1"]))'
               ')')

In [9]:
a = '''ahahaah'''
a

'ahahaah'

* loc

In [10]:
df.loc[df.iloc[:,256]=="sh",:]

,x.1,x.2,x.3,x.4,x.5,x.6,x.7,x.8,x.9,x.10,...,x.249,x.250,x.251,x.252,x.253,x.254,x.255,x.256,g,speaker
row.names,,,,,,,,,,,,,,,,,,,,,
1,9.85770,9.20711,9.81689,9.01692,9.05675,8.92518,11.28308,11.52980,10.79713,9.04747,...,12.68076,11.20767,13.69394,13.72055,12.16628,12.92489,12.51195,9.75527,sh,train.dr1.mcpm0.sa1
8,15.58114,15.53505,13.83707,13.89967,14.59198,14.05211,11.62342,14.33861,15.14155,15.66502,...,9.96958,8.76994,11.33459,12.46203,12.84761,10.98335,9.55326,10.87688,sh,train.dr1.mcpm0.sa1
11,10.88036,12.39941,12.02671,10.43652,9.99188,10.88614,13.10210,13.24739,11.82883,10.31598,...,14.48369,15.16222,14.23441,13.64343,14.12932,14.32961,14.39329,14.94237,sh,train.dr1.mdac0.sa1
18,10.95938,5.91926,11.02607,12.62458,12.62186,12.62043,13.11238,12.80346,13.78933,14.48784,...,13.08466,16.73091,17.27971,16.70878,14.41791,14.28443,16.30518,17.03775,sh,train.dr1.mdac0.sa1
21,10.63970,8.25693,7.67767,5.54465,7.66000,8.83746,10.43225,9.22884,10.21753,8.97281,...,12.65041,15.09566,16.43750,16.45618,15.93877,15.42864,15.60485,14.85353,sh,train.dr1.mdpk0.sa1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4485,11.89307,12.19350,11.77908,11.98719,12.09570,13.38420,12.57996,12.75996,14.59222,15.35107,...,15.01861,13.50174,14.47121,16.69968,16.72827,13.85422,15.30005,14.68819,sh,test.dr8.mpam0.sa1
4488,12.15906,12.19535,12.79793,11.47633,12.19238,10.76935,10.08952,12.60766,12.49327,11.27941,...,12.18814,13.84468,13.02866,14.97519,13.96783,13.54509,15.49848,16.26415,sh,test.dr8.mres0.sa1
4496,12.78718,13.80951,11.95766,12.45540,9.36343,13.19301,13.54617,14.71737,15.09650,14.59488,...,11.66844,11.68869,9.14628,12.64480,8.43527,11.63359,10.79362,11.14416,sh,test.dr8.mres0.sa1
4499,11.29570,8.13999,11.09349,11.50054,8.68173,8.42031,8.67360,8.56148,10.39267,10.28783,...,11.75881,13.31818,13.21644,12.49354,12.72778,11.46897,10.17898,10.50219,sh,test.dr8.mslb0.sa1
4507,12.30174,12.40383,9.06497,12.43750,13.48388,13.52034,12.97796,11.58782,12.54174,14.09863,...,12.83836,10.62525,10.15274,9.59347,10.66338,9.88007,10.82203,12.00199,sh,test.dr8.mslb0.sa1

In [11]:
df.loc[df["g"]=="sh",:]

,x.1,x.2,x.3,x.4,x.5,x.6,x.7,x.8,x.9,x.10,...,x.249,x.250,x.251,x.252,x.253,x.254,x.255,x.256,g,speaker
row.names,,,,,,,,,,,,,,,,,,,,,
1,9.85770,9.20711,9.81689,9.01692,9.05675,8.92518,11.28308,11.52980,10.79713,9.04747,...,12.68076,11.20767,13.69394,13.72055,12.16628,12.92489,12.51195,9.75527,sh,train.dr1.mcpm0.sa1
8,15.58114,15.53505,13.83707,13.89967,14.59198,14.05211,11.62342,14.33861,15.14155,15.66502,...,9.96958,8.76994,11.33459,12.46203,12.84761,10.98335,9.55326,10.87688,sh,train.dr1.mcpm0.sa1
11,10.88036,12.39941,12.02671,10.43652,9.99188,10.88614,13.10210,13.24739,11.82883,10.31598,...,14.48369,15.16222,14.23441,13.64343,14.12932,14.32961,14.39329,14.94237,sh,train.dr1.mdac0.sa1
18,10.95938,5.91926,11.02607,12.62458,12.62186,12.62043,13.11238,12.80346,13.78933,14.48784,...,13.08466,16.73091,17.27971,16.70878,14.41791,14.28443,16.30518,17.03775,sh,train.dr1.mdac0.sa1
21,10.63970,8.25693,7.67767,5.54465,7.66000,8.83746,10.43225,9.22884,10.21753,8.97281,...,12.65041,15.09566,16.43750,16.45618,15.93877,15.42864,15.60485,14.85353,sh,train.dr1.mdpk0.sa1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4485,11.89307,12.19350,11.77908,11.98719,12.09570,13.38420,12.57996,12.75996,14.59222,15.35107,...,15.01861,13.50174,14.47121,16.69968,16.72827,13.85422,15.30005,14.68819,sh,test.dr8.mpam0.sa1
4488,12.15906,12.19535,12.79793,11.47633,12.19238,10.76935,10.08952,12.60766,12.49327,11.27941,...,12.18814,13.84468,13.02866,14.97519,13.96783,13.54509,15.49848,16.26415,sh,test.dr8.mres0.sa1
4496,12.78718,13.80951,11.95766,12.45540,9.36343,13.19301,13.54617,14.71737,15.09650,14.59488,...,11.66844,11.68869,9.14628,12.64480,8.43527,11.63359,10.79362,11.14416,sh,test.dr8.mres0.sa1
4499,11.29570,8.13999,11.09349,11.50054,8.68173,8.42031,8.67360,8.56148,10.39267,10.28783,...,11.75881,13.31818,13.21644,12.49354,12.72778,11.46897,10.17898,10.50219,sh,test.dr8.mslb0.sa1
4507,12.30174,12.40383,9.06497,12.43750,13.48388,13.52034,12.97796,11.58782,12.54174,14.09863,...,12.83836,10.62525,10.15274,9.59347,10.66338,9.88007,10.82203,12.00199,sh,test.dr8.mslb0.sa1

# 统计一列有哪些取值.value_counts()

In [12]:
df["g"]

row.names
1        sh
2        iy
3       dcl
4       dcl
5        aa
       ...
4505     iy
4506     aa
4507     sh
4508     ao
4509     ao
Name: g, Length: 4509, dtype: object

In [13]:
df["g"].value_counts()

iy     1163
ao     1022
sh      872
dcl     757
aa      695
Name: g, dtype: int64

# 按列计算平均值.mean(0)
* 很多统计里面的AXIS值列是0行是1

In [14]:
df.mean(1)

row.names
1       12.833212
2       12.247591
3        5.860802
4        5.752476
5       10.940193
          ...
4505     9.867763
4506    10.545055
4507    12.484223
4508     9.271637
4509     8.793912
Length: 4509, dtype: float64

# 各种算平方

In [15]:
import math

In [16]:
df.mean(0)**2 == np.square(df.mean(0))

x.1      True
x.2      True
x.3      True
x.4      True
x.5      True
         ...
x.252    True
x.253    True
x.254    True
x.255    True
x.256    True
Length: 256, dtype: bool

In [17]:
3**2 == np.square(3) == math.pow(3,2)

True

# 算离差平方和

In [18]:
np.var([1,2,3]) * len([1,2,3])

2.0

# 不能顶头的时候用max

In [19]:
'''
    #根据m,h选择m个markers
    def findmarkers(m,h,F):
        markers=np.zeros(m)
        temp = F.copy()
        for i in range(m):
            markers[i]=np.argmax(temp)
            temp[max(np.argmax(temp)-h+1,0):min(np.argmax(temp)+h,len(temp)-1)]=0
        return markers
    m=7
    h=6
    markers=findmarkers(m,h,F)
    print(markers)
'''

'\n    #根据m,h选择m个markers\n    def findmarkers(m,h,F):\n        markers=np.zeros(m)\n        temp = F.copy()\n        for i in range(m):\n            markers[i]=np.argmax(temp)\n            temp[max(np.argmax(temp)-h+1,0):min(np.argmax(temp)+h,len(temp)-1)]=0\n        return markers\n    m=7\n    h=6\n    markers=findmarkers(m,h,F)\n    print(markers)\n'